# -*- mode: python -*-

Import('env')

env = env.Clone()

env['CCFLAGS'] = ['-Isrc/s2/s2-geometry', '-DS2_USE_EXACTFLOAT', '-DNDEBUG']

env.SConscript(['base/SConscript',
                'strings/SConscript',
                'util/coding/SConscript',
                'util/math/SConscript',
               ],
               'env')

env.Library('s2',
            ['s1angle.cc',
             's2.cc',
             's2cellid.cc',
             's2latlng.cc',
             's1interval.cc',
             's2cap.cc',
             's2cell.cc',
             's2cellunion.cc',
             's2edgeindex.cc',
             's2edgeutil.cc',
             's2latlngrect.cc',
             's2loop.cc',
             's2pointregion.cc',
             's2polygon.cc',
             's2polygonbuilder.cc',
             's2polyline.cc',
             's2r2rect.cc',
             's2region.cc',
             's2regioncoverer.cc',
             's2regionintersection.cc',
             's2regionunion.cc',
            ],           
)
